# Generated by Django 5.2 on 2025-04-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя категории"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя категории"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя категории"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя категории"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="icons/",
                        verbose_name="Иконка категории",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя товара")),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя товара"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя товара"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя товара"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Короткое описание товара"),
                ),
                (
                    "short_description_ru",
                    models.TextField(
                        null=True, verbose_name="Короткое описание товара"
                    ),
                ),
                (
                    "short_description_uz",
                    models.TextField(
                        null=True, verbose_name="Короткое описание товара"
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        null=True, verbose_name="Короткое описание товара"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Полное описание товара"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Полное описание товара"),
                ),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Полное описание товара"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Полное описание товара"),
                ),
                ("price", models.IntegerField(verbose_name="Цена товара")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Скидка товара"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("new", "Новый"), ("popular", "Популярный")],
                        max_length=10,
                        null=True,
                        verbose_name="Статус товара",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="perfumeApp.category",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="perfumeApp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото товара",
                "verbose_name_plural": "Фото товаров",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя подкатегории"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя подкатегории"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя подкатегории"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя подкатегории"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="icons/",
                        verbose_name="Иконка подкатегории",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="perfumeApp.category",
                        verbose_name="Выбор категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_products",
                to="perfumeApp.subcategory",
                verbose_name="Подкатегория товара",
            ),
        ),
    ]
