# Generated by Django 5.2 on 2025-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeApp', '0002_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField(default=False)),
                ('username', models.CharField()),
                ('phone_number', models.CharField()),
                ('slug', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар в обработке',
                'verbose_name_plural': 'Товары в обработке',
            },
        ),
    ]
