# Generated by Django 5.2 on 2025-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeApp', '0003_pendingorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorders',
            name='message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
