# Generated by Django 5.2 on 2025-05-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeApp', '0004_pendingorders_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingorders',
            old_name='slug',
            new_name='name',
        ),
    ]
