# Generated by Django 5.2 on 2025-05-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeApp', '0005_rename_slug_pendingorders_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingorders',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='perfumeApp.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='perfumeApp.subcategory', verbose_name='Подкатегория товара'),
        ),
    ]
