# Generated by Django 5.2 on 2025-05-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeApp', '0006_rename_name_pendingorders_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, null=True, verbose_name='Объем товара'),
        ),
    ]
